In [14]:
import numpy as np

def sigmoid(x):
    """
    Calculate sigmoid
    """
    return 1/(1+np.exp(-x))

def sigmoid_prime(x):
    """
    # Derivative of the sigmoid function
    """
    return sigmoid(x) * (1 - sigmoid(x))

learnrate = 0.5
x = np.array([1, 2, 3, 4])
y = np.array(0.5)

# Initial weights
w = np.array([0.5, -0.5, 0.3, 0.1])

### Calculate one gradient descent step for each weight
### Note: Some steps have been consolidated, so there are
###       fewer variable names than in the above sample code

# TODO: Calculate the node's linear combination of inputs and weights

# h = ∑ x[i]w[i]
h = np.dot(x,w)
#x[0]*w[0] + x[1]*w[1] + x[2]*w[2] + x[3]*w[3]

# Calculate output of neural network
# y_hat = sigma(h)
nn_output = sigmoid(h)

# Calculate error of neural network
# y-y_hat
error = y - nn_output

# Calculate the error term
# E = sigma_prime(h)*(y-y_hat)
error_term = sigmoid_prime(h) * error

# Calculate change in weights
# ∆w = learnrate * E * x[i]
del_w = learnrate * error_term * x
# or
# del_w = [learnrate * error_term * x[0],
#          learnrate * error_term * x[1],
#          learnrate * error_term * x[2],
#          learnrate * error_term * x[3]]

new_weights = w + del_w

print('Neural Network output:')
print(nn_output)
print('Amount of Error:')
print(error)
print('Change in Weights:')
print(del_w)
print('new weights')
print(new_weights)

Neural Network output:
0.6899744811276125
Amount of Error:
-0.1899744811276125
Change in Weights:
[-0.02031869 -0.04063738 -0.06095608 -0.08127477]
new weights
[ 0.47968131 -0.54063738  0.23904392  0.01872523]


In [4]:
np.dot(x,w)

0.7999999999999998

In [13]:
w + del_w

array([ 0.47968131, -0.54063738,  0.23904392,  0.01872523])